import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/Layouts/Header";
import Footer from "@/Components/Layouts/Footer";

import { Locale } from "@/i18n.config";
import { getDictionary } from "@/lib/dictionary";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Params = Promise<{ lang: Locale }>

export default async function RootLayout({
  children,
  params, 
}: {
  children: React.ReactNode;
  params: Params
}) {
  const { lang } = await params;

  const translation = await getDictionary(lang);

  return (
    <html lang={lang}>
      <body>

        <Header lang={lang} translation={translation} />
        {children}
        <Footer lang={lang} translation={translation.footer} />
      </body>
    </html>
  );
}
